file = open("dream.txt", 'w')
file.write("Dream Big: I want to become a skilled programmer who builds systems that help people.")
file.write("Stay Curious: I will keep learning even when things get difficult.\n")
file.write("Embrace Failure: Every error is a step closer to success.\n")
file.write("Create Impact: I want my code to solve real-world problems.\n")
file.write("Be Consistent: Small progress every day leads to big results.\n")
file.write("Believe in Yourself: I am capable of learning and growing.Someday we will be free \n")
file.close()
print("File creating successful")